db_identifier       = "demo-rds-terraform"
dbname              = "testdb"
dbengine            = "mysql"
rds_instance_type   = "db.t3.micro"
engine_version      = "5.7"
username            = "admin"
password            = "jvasccqte7yibxwyst2i2db"
security_group_name = "Demo-rds-sg"
